import { useState } from "react";
import { Pressable, ScrollView, Text, View } from "react-native";
import { useLocalSearchParams } from "expo-router";

import { NextActionCard } from "@/components/learning/next-action-card";
import { NodeTimeline } from "@/components/learning/node-timeline";
import { RatingRow, type ReviewRating } from "@/components/learning/rating-row";
import { SessionSummary } from "@/components/learning/session-summary";
import { WordDetailPanel } from "@/components/learning/word-detail-panel";
import { ScreenContainer } from "@/components/screen-container";
import { AppButton } from "@/components/ui/app-button";
import { AppCard } from "@/components/ui/app-card";
import { AppHeader } from "@/components/ui/app-header";
import { ProgressBar } from "@/components/ui/progress-bar";
import { SectionHeading } from "@/components/ui/section-heading";

const nodes = [
  { id: "pronouns", title: "Pronomes básicos", description: "Reconhecer eu, você e ele.", status: "completed" as const, progressPercent: 100, stepCount: 4, activityCount: 3 },
  { id: "identity", title: "Pessoas e identidade", description: "Falar sobre pessoas próximas.", status: "in_progress" as const, progressPercent: 60, stepCount: 4, activityCount: 3 },
  { id: "intro", title: "Dizer nome", description: "Apresentar seu nome em mandarim.", status: "available" as const, progressPercent: 0, stepCount: 4, activityCount: 3 },
  { id: "ask-name", title: "Perguntar nome", description: "Perguntar e responder nomes.", status: "locked" as const, progressPercent: 0, stepCount: 4, activityCount: 3 },
];

const entry = { id: "wo", hanzi: "我", pinyin: "wǒ", meaningPtBr: "eu / me", exampleHanzi: "我是学生。", examplePtBr: "Eu sou estudante.", status: "learning" as const };

export type PreviewScreen = "home" | "map" | "review" | "library" | "node" | "result";

export function RemodelPreview({ forcedScreen }: { forcedScreen?: PreviewScreen } = {}) {
  const params = useLocalSearchParams<{ screen?: PreviewScreen }>();
  const queryScreen = typeof window !== "undefined" ? parsePreviewScreen(new URLSearchParams(window.location.search).get("screen")) : params.screen;
  const standalone = Boolean(forcedScreen || queryScreen);
  const [screen, setScreen] = useState<PreviewScreen>(forcedScreen ?? queryScreen ?? "home");
  const [revealed, setRevealed] = useState(false);
  const [rating, setRating] = useState<ReviewRating>();
  const [selected, setSelected] = useState(false);
  const previewUser = null;
  const navigate = (value: typeof screen) => { setScreen(value); setRevealed(false); setRating(undefined); };
  return <ScreenContainer className="px-5 pt-3" edges={["top", "left", "right", "bottom"]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 44 }}><View className="mx-auto w-full max-w-6xl gap-6"><AppHeader active={screen === "home" ? "Hoje" : screen === "review" ? "Revisar" : screen === "library" ? "Biblioteca" : "Mapa"} user={previewUser} onLogout={() => undefined} />{!standalone ? <View className="flex-row flex-wrap gap-2"><AppButton label="Hoje" variant={screen === "home" ? "primary" : "secondary"} onPress={() => navigate("home")} /><AppButton label="Mapa" variant={screen === "map" ? "primary" : "secondary"} onPress={() => navigate("map")} /><AppButton label="Revisar" variant={screen === "review" ? "primary" : "secondary"} onPress={() => navigate("review")} /><AppButton label="Biblioteca" variant={screen === "library" ? "primary" : "secondary"} onPress={() => navigate("library")} /><AppButton label="Nó" variant={screen === "node" ? "primary" : "secondary"} onPress={() => navigate("node")} /><AppButton label="Resultado" variant={screen === "result" ? "primary" : "secondary"} onPress={() => navigate("result")} /></View> : null}{screen === "home" ? <HomePreview navigate={navigate} /> : screen === "map" ? <MapPreview navigate={navigate} /> : screen === "review" ? <ReviewPreview revealed={revealed} rating={rating} setRevealed={setRevealed} setRating={setRating} navigate={navigate} /> : screen === "library" ? <LibraryPreview selected={selected} setSelected={setSelected} /> : screen === "node" ? <NodePreview navigate={navigate} /> : <SessionSummary reviewed={1} forgot={0} hard={0} easy={1} onRetryHard={() => navigate("review")} onHome={() => navigate("home")} />}</View></ScrollView></ScreenContainer>;
}

export default RemodelPreview;

function parsePreviewScreen(value: string | null): "home" | "map" | "review" | "library" | "node" | "result" | undefined {
  return value === "home" || value === "map" || value === "review" || value === "library" || value === "node" || value === "result" ? value : undefined;
}

function HomePreview({ navigate }: { navigate: (screen: "home" | "map" | "review" | "library" | "node" | "result") => void }) { return <><SectionHeading eyebrow="SUGESTÃO PARA HOJE" title="Bom dia, Tiago." description="Uma pequena sessão mantém seu mandarim em movimento." /><View className="gap-4 md:flex-row"><View className="flex-1"><NextActionCard title="Revisar 4 cartões" description="Há palavras no intervalo certo para você relembrar agora. Comece com uma sessão curta." ctaLabel="Revisar agora" onPress={() => navigate("review")} /></View><View className="gap-3 md:w-64"><Stat value="4" label="cartões vencidos" /><Stat value="+30 XP" label="XP hoje" /><Stat value="4 dias" label="sequência atual" /></View></View></>; }
function Stat({ value, label }: { value: string; label: string }) { return <AppCard className="min-h-[84px] justify-center gap-1"><Text className="text-2xl font-bold text-foreground">{value}</Text><Text className="text-sm text-muted">{label}</Text></AppCard>; }
function MapPreview({ navigate }: { navigate: (screen: "home" | "map" | "review" | "library" | "node" | "result") => void }) { return <><SectionHeading eyebrow="JORNADA DE COMPETÊNCIAS" title="Seu mapa" description="Avance por pequenas conexões até conseguir se apresentar." /><AppCard tone="sand" className="gap-4"><View className="flex-row justify-between"><View className="flex-1"><Text className="text-xs font-bold uppercase tracking-[1.5px] text-primary">TRILHA ATUAL</Text><Text className="mt-1 text-xl font-bold text-foreground">Pessoas e identidade</Text><Text className="mt-1 text-base text-muted">Aprenda a se apresentar e falar sobre pessoas.</Text></View><Text className="text-2xl font-bold text-primary">2/5</Text></View><ProgressBar value={25} label="Progresso da trilha" fillClassName="bg-warning" /></AppCard><NodeTimeline nodes={nodes} recommendedNodeId="intro" onSelect={() => navigate("node")} /></>; }
function ReviewPreview({ revealed, rating, setRevealed, setRating, navigate }: { revealed: boolean; rating?: ReviewRating; setRevealed: (value: boolean) => void; setRating: (value: ReviewRating) => void; navigate: (screen: "home" | "map" | "review" | "library" | "node" | "result") => void }) { return <><SectionHeading eyebrow="SESSÃO DE REVISÃO" title="Revisar agora" description="3 cartões vencidos · ~3 min" /><AppCard tone="ink" className="items-center gap-5 p-7"><View className="h-16 w-16 items-center justify-center rounded-2xl bg-warning"><Text className="text-3xl font-bold text-foreground">复</Text></View><Text className="text-center text-2xl font-bold text-background">Uma palavra por vez.</Text><Text className="max-w-lg text-center text-base leading-6 text-surface">Recupere o significado antes de revelar a resposta. Seus ratings ajustam o próximo intervalo.</Text><View className="items-center gap-4"><Text className="text-7xl font-bold text-background">我</Text><Text className="text-sm text-surface">Tente lembrar o significado antes de revelar.</Text></View>{revealed ? <View className="w-full gap-4 border-t border-surface/30 pt-5"><Text className="text-center text-xl font-bold text-background">wǒ · eu / me</Text><RatingRow selected={rating} onSelect={setRating} /></View> : <AppButton label="Revelar resposta" onPress={() => setRevealed(true)} />}</AppCard>{rating ? <AppButton label="Ver resultado" onPress={() => navigate("result")} /> : null}</>; }
function LibraryPreview({ selected, setSelected }: { selected: boolean; setSelected: (value: boolean) => void }) { return <><SectionHeading eyebrow="BIBLIOTECA" title="Suas palavras" description="Consulte o que você encontrou e acompanhe seu estado pessoal." /><View className="h-14 justify-center rounded-2xl border border-border bg-surface px-4"><Text className="text-muted">⌕  Buscar hanzi, pinyin ou significado</Text></View><View className="flex-row flex-wrap gap-2"><AppButton label="Minhas palavras" /><AppButton label="Dicionário" variant="secondary" /><AppButton label="Todas" variant="secondary" /><AppButton label="Aprendendo" variant="secondary" /><AppButton label="Conhecidas" variant="secondary" /></View><Pressable onPress={() => setSelected(true)} accessibilityRole="button" accessibilityLabel="Abrir ficha da palavra 我"><AppCard className="flex-row items-center gap-4"><View className="h-14 w-14 items-center justify-center rounded-2xl bg-sand"><Text className="text-2xl font-bold text-primary">我</Text></View><View className="flex-1"><Text className="font-bold text-foreground">eu / me</Text><Text className="text-sm text-primary">wǒ</Text><Text className="text-xs text-muted">Em aprendizado</Text></View><Text className="text-xl text-muted">›</Text></AppCard></Pressable>{selected ? <WordDetailPanel entry={entry} onClose={() => setSelected(false)} onStatus={() => undefined} /> : null}</>; }
function NodePreview({ navigate }: { navigate: (screen: "home" | "map" | "review" | "library" | "node" | "result") => void }) { return <><SectionHeading eyebrow="NÓ DE APRENDIZAGEM" title="Dizer nome" description="Apresentar seu nome e perguntar o nome de outra pessoa." /><AppCard tone="sand" className="gap-4"><Text className="text-xs font-bold uppercase tracking-[1.5px] text-primary">OBJETIVO COMUNICATIVO</Text><Text className="text-2xl font-bold text-foreground">Apresentar seu nome e perguntar o nome de outra pessoa.</Text><ProgressBar value={50} label="Domínio desta etapa" /></AppCard><View className="gap-3 md:flex-row"><View className="flex-1"><Text className="mb-3 text-xl font-bold text-foreground">Uma etapa por vez</Text>{["Objetivo comunicativo", "Vocabulário essencial", "Prática guiada", "Diálogo de apresentação"].map((label, index) => <AppCard key={label} className={`mb-3 flex-row items-center gap-3 ${index === 0 ? "border-primary bg-primary/5" : ""}`}><View className="h-10 w-10 items-center justify-center rounded-full bg-sand"><Text className="font-bold text-primary">{index + 1}</Text></View><View className="flex-1"><Text className="font-bold text-foreground">{label}</Text><Text className="text-sm text-muted">{index === 0 ? "Agora" : index === 1 ? "A seguir" : "Disponível"}</Text></View></AppCard>)}</View><AppCard tone="ink" className="gap-4 md:w-[320px]"><Text className="text-xs font-bold uppercase tracking-[1.5px] text-warning">COMO VOCÊ VAI SABER?</Text><Text className="text-base leading-6 text-background">Você termina quando consegue reconhecer, construir e aplicar a estrutura sem depender da tradução.</Text><AppButton label="Começar etapa" onPress={() => navigate("review")} /></AppCard></View></>; }
