import { Pressable, ScrollView, Text, View } from "react-native";

import { AppButton } from "@/components/ui/app-button";
import { AppCard } from "@/components/ui/app-card";

type ImportItem = { id: string; pathId: string; contentVersion: string; status: string };
const STATUS_LABELS: Record<string, string> = { draft: "Rascunho", review: "Em revisão", published: "Publicado", archived: "Arquivado" };

export function AdminDashboard({ imports, pending, onCreate, onImport, onOpen, onTransition }: { imports: ImportItem[]; pending?: boolean; onCreate: () => void; onImport: () => void; onOpen: (id: string) => void; onTransition: (item: ImportItem) => void }) {
  const count = (status: string) => imports.filter((item) => item.status === status).length;
  const total = imports.length;
  return (
    <View className="gap-6">
      <View className="flex-row items-end justify-between gap-4"><View className="flex-1"><Text className="text-xs font-bold uppercase tracking-[1.5px] text-primary">ÁREA DE ADMINISTRAÇÃO</Text><Text className="mt-2 text-3xl font-bold text-foreground">Visão geral</Text><Text className="mt-2 text-base leading-6 text-muted">Conteúdo pedagógico, atividade editorial e saúde das trilhas em um só lugar.</Text></View><View className="hidden flex-row gap-2 md:flex"><AppButton label="Importar conteúdo" variant="secondary" onPress={onImport} /><AppButton label="Criar nó" onPress={onCreate} /></View></View>
      <View className="flex-row gap-2 md:hidden"><View className="flex-1"><AppButton label="Importar conteúdo" variant="secondary" onPress={onImport} /></View><View className="flex-1"><AppButton label="Criar nó" onPress={onCreate} /></View></View>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }} accessibilityRole="tablist"><AdminTab label="Visão geral" selected /><AdminTab label="Trilhas e nós" /><AdminTab label="Dicionário" /><AdminTab label="Moderação" /></ScrollView>
      <Text className="text-sm text-muted">Última atualização: agora · Dados editoriais da sua conta</Text>
      <View className="flex-row flex-wrap gap-3"><MetricCard value={String(total)} label="conteúdos totais" /><MetricCard value={String(count("draft"))} label="rascunhos" tone="warning" /><MetricCard value={String(count("review"))} label="em revisão" tone="primary" /><MetricCard value={String(count("published"))} label="publicados" tone="success" /></View>
      <View className="gap-4 md:flex-row"><AppCard className="flex-1 gap-4"><View className="flex-row items-center justify-between"><Text className="text-lg font-bold text-foreground">Atividade editorial</Text><Text className="text-sm text-muted">por status</Text></View><StatusBar label="Rascunhos" value={count("draft")} total={Math.max(total, 1)} color="bg-warning" /><StatusBar label="Em revisão" value={count("review")} total={Math.max(total, 1)} color="bg-primary" /><StatusBar label="Publicados" value={count("published")} total={Math.max(total, 1)} color="bg-success" /><Text className="text-sm leading-5 text-muted">Valide conteúdos antes de publicar e crie uma nova versão para alterar material já publicado.</Text></AppCard><AppCard tone="sand" className="flex-1 gap-3"><Text className="text-lg font-bold text-foreground">Itens que precisam de atenção</Text><Text className="text-sm leading-5 text-muted">{count("draft")} {count("draft") === 1 ? "rascunho aguarda" : "rascunhos aguardam"} revisão. Conteúdos publicados permanecem imutáveis.</Text><AppButton label="Ver pendências" variant="secondary" onPress={() => undefined} /></AppCard></View>
      <View className="gap-3"><View className="flex-row items-center justify-between"><View><Text className="text-xl font-bold text-foreground">Gestão de conteúdo</Text><Text className="mt-1 text-sm text-muted">Trilhas e nós importados</Text></View><Text className="text-sm font-bold text-primary">{total} itens</Text></View>{imports.length === 0 ? <AppCard className="gap-2"><Text className="font-bold text-foreground">Ainda não há conteúdo</Text><Text className="text-sm leading-5 text-muted">Importe sua primeira trilha para começar a construir o mapa.</Text></AppCard> : imports.map((item) => <ContentRow key={item.id} item={item} pending={pending} onOpen={() => onOpen(item.id)} onTransition={() => onTransition(item)} />)}</View>
    </View>
  );
}

function AdminTab({ label, selected = false }: { label: string; selected?: boolean }) { return <Pressable accessibilityRole="tab" accessibilityState={{ selected }} className={`min-h-[44px] justify-center rounded-2xl border px-4 ${selected ? "border-primary bg-sand" : "border-border bg-surface"}`}><Text className={`font-bold ${selected ? "text-foreground" : "text-muted"}`}>{label}</Text></Pressable>; }
function MetricCard({ value, label, tone = "default" }: { value: string; label: string; tone?: "default" | "warning" | "primary" | "success" }) { const valueClass = tone === "warning" ? "text-warning" : tone === "primary" ? "text-primary" : tone === "success" ? "text-success" : "text-foreground"; return <AppCard className="min-w-[145px] flex-1 gap-1 p-4"><Text className={`text-3xl font-bold ${valueClass}`}>{value}</Text><Text className="text-sm text-muted">{label}</Text></AppCard>; }
function StatusBar({ label, value, total, color }: { label: string; value: number; total: number; color: string }) { return <View className="gap-2"><View className="flex-row justify-between"><Text className="text-sm font-semibold text-foreground">{label}</Text><Text className="text-sm text-muted">{value}</Text></View><View className="h-2 overflow-hidden rounded-full bg-border"><View className={`h-full rounded-full ${color}`} style={{ width: `${Math.round((value / total) * 100)}%` }} /></View></View>; }
function ContentRow({ item, pending, onOpen, onTransition }: { item: ImportItem; pending?: boolean; onOpen: () => void; onTransition: () => void }) { const published = item.status === "published"; return <AppCard className="gap-4"><View className="flex-row items-start justify-between gap-3"><View className="flex-1 gap-1"><Text className="text-lg font-bold text-foreground">{item.pathId}</Text><Text className="text-sm text-muted">Versão {item.contentVersion}</Text></View><Text className="rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary">{STATUS_LABELS[item.status] ?? item.status}</Text></View><View className="flex-row gap-2"><AppButton label="Abrir" variant="quiet" onPress={onOpen} /><AppButton label={published ? "Publicado" : "Enviar para revisão"} variant="secondary" loading={pending} disabled={published} onPress={onTransition} /></View></AppCard>; }
